### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Urchmaney** [Urchmaney/Quest#33]
- [ ] Create models structure
- [ ] API for all user created hackathons
- [ ] API creating hackathon
